- name: Configure Active Directory
  hosts: savard-server
  tasks:
    - name: Install AD Domain Services
      win_feature:
        name: AD-Domain-Services
        include_management_tools: yes
        state: present

    - name: Promote server to domain controller
      win_domain_controller:
        dns_domain_name: savard.local
        safe_mode_password: "P@ssw0rd1234!"
        domain_netbios_name: SAVARD
        state: domain_controller