- name: Create users and groups
  hosts: savard-server
  tasks:
    - name: Create groups
      win_group:
        name: "{{ item.name }}"
        scope: "{{ item.scope }}"
        category: "{{ item.category }}"
        path: "OU={{ item.ou }},DC=savard,DC=local"
      loop:
        - { name: "VentesEtMarketing_Group", scope: "global", category: "security", ou: "VentesEtMarketing" }
        - { name: "RechercheEtDeveloppement_Group", scope: "global", category: "security", ou: "RechercheEtDeveloppement" }

    - name: Create users
      win_user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        state: present
        groups: "{{ item.groups }}"
      loop:
        - { name: "user1", password: "P@ssw0rd1234!", groups: ["VentesEtMarketing_Group"] }
        - { name: "user2", password: "P@ssw0rd1234!", groups: ["RechercheEtDeveloppement_Group"] }