galaxy_info:
  author: votre_nom
  description: Rôle pour configurer Active Directory sur un serveur Windows.
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Windows
      versions:
        - 2016
        - 2019

dependencies: []