---
- hosts: savard-server
  gather_facts: no
  vars:
    domain_name: "savard.local"
    departments:
      - name: "Ventes et Marketing"
        users:
          - username: "ventes1"
          - username: "ventes2"
      - name: "Recherche et Développement"
        users:
          - username: "recherche1"
          - username: "recherche2"
      - name: "Finances"
        users:
          - username: "finances1"
          - username: "finances2"
      - name: "Technologies de l'information"
        users:
          - username: "ti1"
          - username: "ti2"
      - name: "Sondages"
        users:
          - username: "sondages1"
          - username: "sondages2"
  roles:
    - ad  # Le rôle 'ad' qui contient les tâches définies dans tasks/main.yml