---
- name: Configurer le pare-feu Windows et activer WinRM
  hosts: all
  tasks:
    - name: Ouvrir le port WinRM (5985)
      ansible.windows.win_firewall_rule:
        name: "WinRM HTTP"
        localport: 5985
        action: allow
        direction: in
        protocol: TCP
        enabled: yes

    - name: Désactiver complètement le pare-feu Windows (⚠️ temporaire pour tests)
      ansible.windows.win_feature:
        name: "Windows-Defender-Features"
        state: absent

    - name: Vérifier si WinRM est activé
      ansible.windows.win_shell: |
        Get-Service WinRM
      register: winrm_status

    - name: Afficher l'état de WinRM
      debug:
        var: winrm_status.stdout_lines
