---
- name: Configurer WinRM sur le serveur Windows
  hosts: all
  gather_facts: no
  tasks:
    - name: Activer WinRM
      ansible.windows.win_shell: winrm quickconfig -q

    - name: Activer l'authentification Basic
      ansible.windows.win_shell: winrm set winrm/config/service/auth '@{Basic="true"}'

    - name: Désactiver UAC pour l'accès distant
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
        name: LocalAccountTokenFilterPolicy
        data: 1
        type: dword

    - name: Ajouter adminuser au groupe Administrateurs
      ansible.windows.win_group_membership:
        name: Administrateurs
        members: adminuser
        state: present

    - name: Redémarrer WinRM
      ansible.windows.win_service:
        name: WinRM
        state: restarted
