---
- name: Installer le rôle DNS Server
  ansible.windows.win_feature:
    name: DNS
    include_management_tools: yes
    state: present

- name: Vérifier la présence des modules Windows
  ansible.builtin.command: ansible-doc -l
  register: ansible_modules_list

- name: Filtrer les modules Windows
  ansible.builtin.debug:
    msg: "{{ ansible_modules_list.stdout_lines | select('search', 'win_') | list }}"

- name: Promouvoir le serveur en contrôleur de domaine
  ansible.windows.win_domain_controller:
    domain_name: "{{ domain_name }}"
    safe_mode_password: "{{ admin_password }}"
    state: domain_controller
  notify: Redémarrer le serveur


- name: Attendre que le serveur redémarre après la promotion
  ansible.windows.win_reboot:
    msg: "Redémarrage du serveur après la promotion en contrôleur de domaine"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30

- name: Créer les unités d'organisation (OU)
  microsoft.ad.ou:
    name: "{{ item.name }}"
    path: "DC={{ domain_name | replace('.', ',DC=') }}"
    state: present
  loop: "{{ departments }}"

- name: Créer les utilisateurs
  ansible.windows.win_user:
    name: "{{ item.1.username }}"
    password: "{{ item.1.password }}"
    state: present
    path: "OU={{ item.0.name }},DC={{ domain_name | replace('.', ',DC=') }}"
  loop: "{{ departments | subelements('users') }}"
  loop_control:
    label: "{{ item.1.username }}"

- name: Créer les groupes
  ansible.windows.win_group:
    name: "{{ item.name }}"
    scope: global
    category: security
    state: present
    path: "OU={{ item.name }},DC={{ domain_name | replace('.', ',DC=') }}"
  loop: "{{ departments }}"

- name: Ajouter les utilisateurs aux groupes
  ansible.windows.win_group_membership:
    name: "{{ item.0.name }}"
    members: "{{ item.1.username }}"
    state: present
  loop: "{{ departments | subelements('users') }}"
  loop_control:
    label: "{{ item.1.username }}"

# Configuration des GPOs
- name: Configurer les stratégies de mot de passe avec PowerShell
  ansible.windows.win_shell: |
    Set-LocalUser -Name "adminuser" -PasswordNeverExpires $false
    net accounts /minpwlen:12
    net accounts /maxpwage:90
    net accounts /uniquepw:24
    net accounts /lockoutthreshold:5
    net accounts /lockoutwindow:30
    net accounts /lockoutduration:30
  register: powershell_result

- name: Afficher le résultat de PowerShell
  ansible.builtin.debug:
    msg: "{{ powershell_result.stdout }}"




# Création des répertoires partagés et configuration des permissions ACL
- name: Créer les dossiers partagés pour chaque département
  ansible.windows.win_file:
    path: "C:\\Shares\\{{ item.name }}"
    state: directory
  loop: "{{ departments }}"

- name: Configurer les permissions ACL pour les dossiers partagés
  ansible.windows.win_acl:
    path: "C:\\Shares\\{{ item.name }}"
    user: "{{ item.name }}"  # Le groupe du département
    rights: FullControl
    state: present
  loop: "{{ departments }}"

- name: Partager les dossiers des départements
  ansible.windows.win_share:
    name: "{{ item.name }}"
    path: "C:\\Shares\\{{ item.name }}"
    description: "Partage pour le département {{ item.name }}"
    full: "{{ item.name }}"
    state: present
  loop: "{{ departments }}"
