---
- name: Installer le rôle AD DS
  ansible.windows.win_feature:
    name: AD-Domain-Services
    include_management_tools: yes
    state: present

- name: Vérifier la présence des modules Windows
  ansible.builtin.command: ansible-doc -l
  register: ansible_modules_list

- name: Filtrer les modules Windows
  ansible.builtin.debug:
    msg: "{{ ansible_modules_list.stdout_lines | select('search', 'win_') | list }}"


- name: Promouvoir le serveur en contrôleur de domaine
  ansible.windows.win_domain_controller:
    dns_domain_name: "{{ domain_name }}"
    safe_mode_password: "{{ admin_password }}"
    state: present
  notify: Redémarrer le serveur

- name: Attendre que le serveur redémarre après la promotion
  ansible.windows.win_reboot:

- name: Créer les unités d'organisation (OU)
  ansible.windows.win_domain_ou:
    name: "{{ item.name }}"
    path: "DC={{ domain_name.split('.')[0] }},DC={{ domain_name.split('.')[1] }}"
    state: present
  loop: "{{ departments }}"

- name: Créer les utilisateurs
  ansible.windows.win_user:
    name: "{{ item.1.username }}"
    password: "{{ item.1.password }}"
    state: present
    path: "OU={{ item.0.name }},DC={{ domain_name.split('.')[0] }},DC={{ domain_name.split('.')[1] }}"
  loop: "{{ departments | subelements('users') }}"
  loop_control:
    label: "{{ item.1.username }}"

- name: Créer les groupes
  ansible.windows.win_group:
    name: "{{ item.name }}"
    scope: global
    category: security
    state: present
    path: "OU={{ item.name }},DC={{ domain_name.split('.')[0] }},DC={{ domain_name.split('.')[1] }}"
  loop: "{{ departments }}"

- name: Ajouter les utilisateurs aux groupes
  ansible.windows.win_group_membership:
    name: "{{ item.0.name }}"
    members: "{{ item.1.username }}"
    state: present
  loop: "{{ departments | subelements('users') }}"
  loop_control:
    label: "{{ item.1.username }}"
