---
- name: Installer le rôle AD DS
  ansible.windows.win_feature:
    name: AD-Domain-Services
    include_management_tools: yes
    state: present

- name: Vérifier la présence des modules Windows
  ansible.builtin.command: ansible-doc -l
  register: ansible_modules_list

- name: Filtrer les modules Windows
  ansible.builtin.debug:
    msg: "{{ ansible_modules_list.stdout_lines | select('search', 'win_') | list }}"

- name: Promouvoir le serveur en contrôleur de domaine
  ansible.windows.win_domain_controller:
    dns_domain_name: "{{ domain_name }}"
    safe_mode_password: "{{ admin_password }}"
    state: present
  notify: Redémarrer le serveur

- name: Attendre que le serveur redémarre après la promotion
  ansible.windows.win_reboot:
    msg: "Redémarrage du serveur après la promotion en contrôleur de domaine"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30

- name: Créer les unités d'organisation (OU)
  ansible.windows.win_domain_ou:
    name: "{{ item.name }}"
    path: "DC={{ domain_name.split('.')[0] }},DC={{ domain_name.split('.')[1] }}"
    state: present
  loop: "{{ departments }}"

- name: Créer les utilisateurs
  ansible.windows.win_user:
    name: "{{ item.1.username }}"
    password: "{{ item.1.password }}"
    state: present
    path: "OU={{ item.0.name }},DC={{ domain_name.split('.')[0] }},DC={{ domain_name.split('.')[1] }}"
  loop: "{{ departments | subelements('users') }}"
  loop_control:
    label: "{{ item.1.username }}"

- name: Créer les groupes
  ansible.windows.win_group:
    name: "{{ item.name }}"
    scope: global
    category: security
    state: present
    path: "OU={{ item.name }},DC={{ domain_name.split('.')[0] }},DC={{ domain_name.split('.')[1] }}"
  loop: "{{ departments }}"

- name: Ajouter les utilisateurs aux groupes
  ansible.windows.win_group_membership:
    name: "{{ item.0.name }}"
    members: "{{ item.1.username }}"
    state: present
  loop: "{{ departments | subelements('users') }}"
  loop_control:
    label: "{{ item.1.username }}"

# Configuration des GPOs
- name: Configurer les GPOs - Stratégies de mot de passe
  community.windows.win_group_policy:
    name: "Password Policy"
    path: "DC={{ domain_name.split('.')[0] }},DC={{ domain_name.split('.')[1] }}"
    setting: 
      MinimumPasswordLength: 12
      MaximumPasswordAge: 90
      PasswordHistorySize: 24
      LockoutBadCount: 5
      ResetLockoutCount: 30
      LockoutDuration: 30
    state: present

# Création des répertoires partagés et configuration des permissions ACL
- name: Créer les dossiers partagés pour chaque département
  ansible.windows.win_file:
    path: "C:\\Shares\\{{ item.name }}"
    state: directory
  loop: "{{ departments }}"

- name: Configurer les permissions ACL pour les dossiers partagés
  ansible.windows.win_acl:
    path: "C:\\Shares\\{{ item.name }}"
    user: "{{ item.name }}"  # Le groupe du département
    rights: FullControl
    state: present
  loop: "{{ departments }}"

- name: Partager les dossiers des départements
  ansible.windows.win_share:
    name: "{{ item.name }}"
    path: "C:\\Shares\\{{ item.name }}"
    description: "Partage pour le département {{ item.name }}"
    full: "{{ item.name }}"
    state: present
  loop: "{{ departments }}"
